name: Build and Release

permissions:
    contents: write # To create releases

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install | npm install pkg

            - name: Build for Linux
              run: npm run build-linux

            - name: Build for Windows
              run: npm run build-windows

            - name: Upload Linux artifact
              uses: actions/upload-artifact@v4
              with:
                  name: lightspreader-linux
                  path: dist/lightspreader

            - name: Upload Windows artifact
              uses: actions/upload-artifact@v4
              with:
                  name: lightspreader-windows
                  path: dist/lightspreader.exe

    release:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download Linux artifact
              uses: actions/download-artifact@v4
              with:
                  name: lightspreader-linux
                  path: dist/

            - name: Download Windows artifact
              uses: actions/download-artifact@v4
              with:
                  name: lightspreader-windows
                  path: dist/

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      dist/lightspreader
                      dist/lightspreader.exe
